<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>自定义Promise_使用测试</title>
</head>

<body>
  <script src="./lib/Promise.js"></script>
 <!-- 
 <script>
    const p = new Promise((resolve, reject) => {
      // throw new Error('---')
      if (Date.now()%2===0) {
        resolve('成功的数据')
      } else {
        reject('失败的数据')
      }
    })
    console.log(p)
    p.then(
      value => {
        console.log('onResolved()1', value)
      },
      reason => {
        console.log('onRejected()1', reason)
      }
    )
    p.then(
      value => {
        console.log('onResolved()2', value)
      },
      reason => {
        console.log('onRejected()2', reason)
      }
    )
  </script>
 -->
<!-- 
 <script>
    new Promise((resolve, reject) => { // 在Promise内部会同步执行executor函数
      resolve(1)
      // reject(2)
    }).then(
      value => {
        console.log('onResolved()', value)
        // return undefined
        // return 3
        // throw 4
        return new Promise((resolve, reject) => {
          resolve(5)
          // reject(6)
        })
      },
      reason => {
        console.log('onRejected()', reason)
      },
    ).then(
      null,
      reason => {
        console.log('onRejected()2', reason)
      }
    ).then(
      value => {
        console.log('onResolved()3')
        throw new Error('xxxxx')
      }
    ).then(value => {
      console.log('onResolved()4')
    }).then(value => {
      console.log('onResolved()5')
    }).catch(reason => {
      console.log('失败了', reason)
    }).then(
      value => {
        console.log('onResolved()6')
        return new Promise(() => {})  // 返回的是永远是pending的promise, 整个链式调用在此中断
      },
      reason => {
        console.log('onRejected()6')
      }
    ).then(value => {
      console.log('onResolved()7')
    }).then(value => {
      console.log('onResolved()8')
    })

    /* 
    promise错误透传
    中断promise链
    */

 </script> -->

 <script>
   const p1 = Promise.resolve(3)
   const p2 = Promise.resolve(Promise.reject(5))
   const p3 = Promise.reject(6)
   console.log(p1, p2, p3)
 </script>
</body>
</html>